# Generated by Django 4.2.6 on 2023-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_module_number_of_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='number_of_tests',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
